main: io.github.ledlamp.mppbridge.Main
name: MPPBridge
version: 1.0
author: Lamp
description: Bridges www.multiplayerpiano.com to Minecraft
commands:
  mpp:
    description: Shows info about the MPP Bridge
    permission: mppbridge.mpp
  mppconnect:
    description: Connects to the MPP room (defaults to lobby)
    permission: mppbridge.connect
  mppdisconnect:
    description: Disconnects the MPP client
    permission: mppbridge.disconnect
  mppsay:
    aliases: ms
    description: Sends a chat message to MPP
    usage: "Usage: /<command> <message>"
    permission: mppbridge.say
  mpptogglechat:
    description: Toggles broadcasting MPP chat messages
    permission: mppbridge.togglechat